theme = "marcorentap"

[editor]
line-number = "relative"
true-color = true
mouse = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]
  right = ["diagnostics", "file-type", "file-encoding", "file-line-ending", "position", "total-line-numbers"]
