[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nasm"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }


#[language-server.rust-analyzer.config]
#command = "clippy"
